server:
  port: 9000

spring:
  application:
    name: wordscore-engine
  profiles:
    active: dev

simplejob:
  frequency: 1000

first:
  job:
    frequency: 1000

second:
  job:
    frequency: 1000

third:
  job:
    frequency: 1000
